language: go

go:
    - 1.8.3
    - 1.9rc1

cache:
    directories:
        - $HOME/ninjabin

install:
    - ./.travis.install-ninja.sh
    - export PATH=$PATH:~/ninjabin

before_script:
    - source .travis.fix-fork.sh

script:
    - export GOROOT=$(go env GOROOT)
    - ./.travis.gofmt.sh
    - go test ./...
    - ./tests/test.sh
    - ./tests/test_tree_tests.sh
    - ./tests/test_tree_tests.sh -t
